Project/handcam/annotator/routes.py
from flask import Flask,render_template, request, Blueprint,flash,redirect,url_for
from handcam.models import rigDeviceData
from handcam.extensions import db
from flask_login import current_user, login_required
from flask import current_app as curr_app
from werkzeug.utils import secure_filename
import os,errno,json
import pandas as pd
from datetime import datetime
from handcam.main.imageStabilization import apply_imageStabilization
from handcam.main.thresholdAlgorithm import apply_thresholdAlgo
from handcam.main.csvAddition import roundThreeAddingtoCSV

annotator = Blueprint('annotator', __name__)

global result

@annotator.route("/annHome",methods=['GET','POST'])
@login_required
def home():
	if current_user.is_authenticated and current_user.isAnnotator==1:
		rigData = rigDeviceData.query.all()
		print(rigData)
		return render_template('annotator/home-ann.html',rigData=rigData,user=current_user)

@annotator.route("/round3/<fileId>", methods=['GET','POST'])
@login_required
def roundThree(fileId):
	if current_user.is_authenticated and current_user.isAnnotator==1:
		# imagedata = []
		# timedata = []
		rigValue =  rigDeviceData.query.filter_by(id=fileId).first_or_404()
		# print(rigValue)
		result = json.loads(rigValue.fileContent)
		timedata = result['timeFrame']
		print("Round 3 display code is running...")
		fresult = timeFrameData(timedata)
		filePath = curr_app.root_path + (rigValue.filePath).split(".zip")[0] + "/updated_csv/afterRound1.csv"
		if not os.path.exists(filePath):
			flash(" No filePath for fetching isgrasping exists")
			return render_template('annotator/round3.html',title='Round 3',fileId = fileId, timedata = fresult)
		else:
			pdValues = pd.read_csv(filePath)
			row = pdValues.index[pdValues['isGrasping'] == 1]
			length = len(row)
			print(length)
			return render_template('annotator/round3.html',title='Round 3',fileId = fileId, timedata = fresult,isgrasping=length)
		# flash('Click on time frame to get the data','info')
		return render_template('annotator/round3.html',title='Round 3',fileId = fileId, timedata = fresult)
	else:
		return redirect(url_for('users.login'))

@annotator.route("/roundThreeSave/<fileId>", methods=['GET', 'POST'])
@login_required
def roundThreeSave(fileId):
	print("entered")
	if current_user.is_authenticated and current_user.isAnnotator==1:
		if request.method == 'POST':
			data = (request.json['tagData'])
			for value in data:
					print(value)
			rigValue =  rigDeviceData.query.filter_by(id=fileId).first_or_404()
			print(rigValue.annotatorTag)
			if rigValue.annotatorTag != None and rigValue.annotatorTag!="null":
				tags = json.loads(rigValue.annotatorTag)
				print("already present : ")
				print(tags)
				for value in data:
					tags[value] = data[value]
				rigValue.annotatorTag = json.dumps(tags)	
			else:
				tags = {}
				for value in data:
					tags[value] = data[value]
				rigValue.annotatorTag = json.dumps(tags)
			db.session.add(rigValue)
			db.session.commit()
			return json.dumps({'fileId':fileId,'flag':'success'})
			
	else:
		return redirect(url_for('users.login'))

@annotator.route("/round3Data/<fileId>", methods=['GET','POST'])
@login_required
def roundThreeData(fileId):
	print("RoundThree data code is running...")
	if current_user.is_authenticated and current_user.isAnnotator==1:
		if request.method == 'POST':
			formTime = request.form['time']
			print(formTime)
			timeSelected = formTime.split('(')[0]
			timeFrame = (formTime.split('(')[1]).split(')')[0]
			imagedata = []
			timedata = []
			rigValue =  rigDeviceData.query.filter_by(id=fileId).first_or_404()
			# print(rigValue)
			result = json.loads(rigValue.fileContent)
			timedata = result['timeFrame']
			imagedata = result['videoNum'][timeFrame]
			fresult = timeFrameData(timedata)
			return render_template('annotator/round3.html',title='round3', fileId = fileId, timedata = fresult, imagedata = imagedata)
		else:
			imagedata = []
			timedata = []
			rigValue =  rigDeviceData.query.filter_by(id=fileId).first_or_404()
			print(rigValue)
			result = json.loads(rigValue.fileContent)
			timedata = result['timeFrame']
			print("Round 3 display code is running...")
			fresult = timeFrameData(timedata)
			return render_template('annotator/round3.html',title='round3',fileId = fileId, timedata = fresult)
	else:
		return redirect(url_for('users.login'))

def timeFrameData(timedata):
	tnums = sorted(timedata.keys())
	fresult = {}
	for value in tnums:
		fresult[value] = timedata[value]
	return fresult


@annotator.route("/roundThreeSubmit/<fileId>", methods=['GET', 'POST'])
@login_required
def roundThreeSubmit(fileId):
	if current_user.is_authenticated and current_user.isAnnotator==1:
		if request.method == 'POST':
			rigValue =  rigDeviceData.query.filter_by(id=fileId).first_or_404()
			filePath = curr_app.root_path + (rigValue.filePath).split(".zip")[0]
			data = json.loads(rigValue.annotatorTag)
			apply_thresholdAlgo(filePath)
			roundThreeAddingtoCSV(filePath,data)
			rigValue.annotator_status=1
			db.session.add(rigValue)
			db.session.commit()
			return json.dumps({'fileId':fileId,'flag':'success'})
			
	else:
		return redirect(url_for('users.login'))

Project/handcam/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from handcam.extensions import db, bcrypt
from handcam.models import User
from handcam.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from handcam.users.utils import  send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        if current_user.isAnnotator==1:
            return redirect(url_for('annotator.home'))
        else:
            return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, rigName=form.rigname.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user.isAnnotator==1:
            return redirect(url_for('annotator.home'))
        else:
            return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            if user.isAnnotator == 1:
                return redirect(url_for('annotator.home'))
            else:
                next_page = request.args.get('next')
                print(next_page)
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    if current_user.is_authenticated and current_user.isAnnotator==0:
        form = UpdateAccountForm()
        if form.validate_on_submit():
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.rigName = form.rigname.data
            db.session.commit()
            flash('Your account has been updated!', 'success')
            return redirect(url_for('users.account'))
        elif request.method == 'GET':
            form.username.data = current_user.username
            form.email.data = current_user.email
            form.rigname.data = current_user.rigName
        image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
        return render_template('account.html', title='Account',
                            image_file=image_file, form=form)
    else:
        return "404 Error"







@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

Project/handcam/templates/annotator/home-ann.html
{% extends "annotator/layout1.html" %}
{% block content %}
<div class="row">
	<div class="col-md-12"></div>
    <div class="col-md-12">
     <div class="content-section">
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>userId</th>
                <th>FileName</th>
                <th>FilePath</th>
                <!-- <th>FileContent</th> -->
                <th>Date</th>
                <th>Status</th>
                <th>annotator_status</th>
            </tr>
        </thead>
        {% if rigData %}
        <tbody>
            {% for value in rigData %}
            <tr>
                <td>{{value.user_id}}</td>
                {% if value.annotator_status == 0 %}
                    {% if value.status == 1 %}
                        <td><a href="{{ url_for('annotator.roundThree', fileId=value.id) }}" >{{value.filename}}</a></td>
                    {% elif value.status == 0 %}
                        <td><p>{{value.filename}}</p></td>
                    {% endif %}
                {% else %}
                    <td><p>{{value.filename}}</p></td>
                {% endif %}
                <td>{{value.filePath}}</td>
                <!-- <td>{{value.fileContent}}</td> -->
                <td>{{value.uploaded_at}}</td>
                <td>{{value.status}}</td>
                <td>{{value.annotator_status}}</td>
            </tr>
            {% endfor %}
        </tbody>
        {% endif %}
    </table>
</div>
</div>
</div>
{% endblock content %}

Project/handcam/templates/annotator/layout1.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">

    {% if title %}
        <title>HandCam - {{ title }}</title>
    {% else %}
        <title>HandCam</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">HandCam</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('annotator.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}
          {% endblock %}
        </div>
        
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->




    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js'></script>

    <script type="text/javascript">
      $(document).ready(function() {
        $('#example').DataTable();
      });
    </script>
    
    
</body>
</html>